version: '3.3'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
        container_name: elasticsearch
        restart: always
        environment:
            - xpack.security.http.ssl.enabled=false
            - discovery.type=single-node
            - ELASTIC_PASSWORD=123456789
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        volumes:
            - ./esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - elastic

volumes:
    esdata:
networks:
    elastic:
        driver: bridge
